var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},h),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!h.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=h.print||console.log.bind(console),m=h.printErr||console.error.bind(console);Object.assign(h,da);da=null;h.arguments&&(ea=h.arguments);h.thisProgram&&(fa=h.thisProgram);var ma=h.wasmBinary,na,p=!1,oa,r,u,pa,qa,v,w,x,ra,y,ka=a=>a.startsWith("file://");
function ta(a,b){function c(){var n=0,q=0;do{var t=f[e++];n+=(t&127)<<q;q+=7}while(t&128);return n}function d(){var n=c();c();0!=(n&1)&&c()}var e=8,g=0;this.pc={};this.lc=[];this.oc={};var f=a;a:for(;e<f.length;){a=f[e++];var l=c()+e;switch(a){case 2:for(a=c();0<a--;)switch(e=c()+e,e=c()+e,f[e++]){case 0:++g;c();break;case 1:c();d();break;case 2:d();break;case 3:e+=2;break;case 4:++e,c()}break;case 10:for(a=c();0<a--;)l=c(),this.pc[g++]=e,this.lc.push(e),e+=l;break a}e=l}b=WebAssembly.Module.customSections(b,
"name");if(b=b.length?b[0]:void 0)for(f=new Uint8Array(b),e=0;e<f.length;)if(b=f[e++],g=c(),1!=b)e+=g;else for(a=c();0<a--;)b=c(),g=c(),this.oc[b]=z(f,e,g),e+=g}var A=0,B=null;function ua(a){h.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==va&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a),d=await WebAssembly.instantiate(c,b);new ta(c,d.module);return d}catch(e){m(`failed to asynchronously prepare wasm: ${e}`),ua(e)}}
async function ya(a){var b=va;if(!ma&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"}),d=(await c).clone(),e=await WebAssembly.instantiateStreaming(c,a),g=await d.arrayBuffer();try{new ta(new Uint8Array(g),e.module)}catch(f){m(`failed to initialize offset-converter: ${f}`)}return e}catch(f){m(`wasm streaming compile failed: ${f}`),m("falling back to ArrayBuffer instantiation")}return xa(b,a)}
class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Aa)return Aa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ba=a=>{for(;0<a.length;)a.shift()(h)},Ca=[],Da=[],Ea=()=>{var a=h.preRun.shift();Da.unshift(a)},Fa=h.noExitRuntime||!0,Ga=0,C={},Ha=a=>{a instanceof za||"unwind"==a||ha(1,a)},Ia=a=>{oa=a;Fa||0<Ga||(h.onExit?.(a),p=!0);ha(a,new za(a))},Ja=a=>{oa=a;Ia(a)},Ka=()=>{if(!(Fa||0<Ga))try{var a=oa;oa=a;Ia(a)}catch(b){Ha(b)}},La=a=>{if(!p)try{a(),Ka()}catch(b){Ha(b)}},Sa=(a,b)=>{Ma=a;Na=b;if(D)if(Oa||=!0,0==a)E=function(){setTimeout(G,Math.max(0,Pa+b-performance.now())|0)};else if(1==a)E=function(){Qa(G)};
else if(2==a){if("undefined"==typeof Ra)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ra=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ra=setImmediate;E=function(){Ra(G)}}},ab=(a,b,c,d,e)=>{function g(){return f<Ta?(Ka(),!1):!0}D=a;Ua=d;var f=Ta;Oa=
!1;G=function(){if(!p)if(0<Va.length){var l=Va.shift();l.nd(l.ad);if(Wa){var n=Wa,q=0==n%1?n-1:Math.floor(n);Wa=l.cd?q:(8*n+(q+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Wa??0,q=Xa.jd??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(G,0)}else if(g())if(Ya=Ya+1|0,1==Ma&&1<Na&&0!=Ya%Na)E();else{0==Ma&&(Pa=performance.now());a:if(!p){for(l of Za)if(!1===l())break a;La(a);for(n of $a)n()}g()&&E()}};e||(0<b?Sa(0,1E3/b):
Sa(1,1),E());if(c)throw"unwind";},Oa=!1,E=null,Ta=0,D=null,Ua=0,Ma=0,Na=0,Ya=0,Va=[],Za=[],$a=[];function bb(){E=null;Ta++}var H=0;function Qa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===H)H=b+1E3/60;else for(;b+2>=H;)H+=1E3/60;setTimeout(a,Math.max(H-b,0))}}var Xa={},Pa,G,Ra,Wa;function cb(a){var b=I.ec[a];b.target.removeEventListener(b.dc,b.Jc,b.fc);I.ec.splice(a,1)}
function db(){if(navigator.userActivation?navigator.userActivation.isActive:I.wc&&I.Wc.uc){var a=I.kc;I.kc=[];for(var b of a)b.zc(...b.Fc)}}function J(a){if(!a.target)return-4;if(a.hc)a.Jc=function(c){++I.wc;I.Wc=a;db();a.ic(c);db();--I.wc},a.target.addEventListener(a.dc,a.Jc,a.fc),I.ec.push(a);else for(var b=0;b<I.ec.length;++b)I.ec[b].target==a.target&&I.ec[b].dc==a.dc&&cb(b--);return 0}function eb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var I={bd:0,od:0,xc:0,tc:0,Dc:0,Bc:0,vc:0,gd:0,td:0,ed:0,md:0,yc:0,Cd:0,Ac:0,qd(a,b,c){r.set(r.subarray(b,b+c),a)},vd(){for(;I.ec.length;)cb(I.ec.length-1);I.kc=[]},wc:0,kc:[],dd(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of I.kc)if(e.zc==a&&d(e.Fc,c))return;I.kc.push({zc:a,Nc:b,Fc:c});I.kc.sort((g,f)=>g.Nc<f.Nc)},xd(a){I.kc=I.kc.filter(b=>b.zc!=a)},ec:[],wd:(a,b)=>{for(var c=0;c<I.ec.length;++c)I.ec[c].target!=a||b&&b!=I.ec[c].dc||
cb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},fb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?z(u,a):"":a;return fb[a]||("undefined"!=typeof document?document.querySelector(a):null)},gb=a=>0>fb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},hb=[],ib,L=a=>{var b=hb[a];b||(a>=hb.length&&(hb.length=a+1),hb[a]=b=ib.get(a));return b},M=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=
0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},jb=(a,b,c,d,e,g)=>{I.vc||(I.vc=N(256));a={target:K(a),dc:g,hc:d,ic:(f=event)=>{var l=f.target.id?f.target.id:"",n=I.vc;M(eb(f.target),n+0,
128);M(l,n+128,128);L(d)(e,n,b)&&f.preventDefault()},fc:c};return J(a)},kb=(a,b,c,d,e,g)=>{I.xc||(I.xc=N(160));a={target:K(a),dc:g,hc:d,ic:f=>{var l=I.xc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);L(d)(e,l,b)&&f.preventDefault()},fc:c};return J(a)},lb=(a,b,c)=>{y[a>>
3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=gb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,g)=>{I.tc||(I.tc=N(64));a=K(a);return J({target:a,uc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,dc:g,hc:d,ic:(f=event)=>{lb(I.tc,f,a);L(d)(e,I.tc,b)&&f.preventDefault()},fc:c})},
mb=(a,b,c,d,e)=>{I.yc||(I.yc=N(257));return J({target:a,dc:e,hc:d,ic:(g=event)=>{var f=I.yc,l=document.pointerLockElement||document.lc||document.pc||document.oc;r[f]=!!l;var n=l?.id||"";M(eb(l),f+1,128);M(n,f+129,128);L(d)(20,f,b)&&g.preventDefault()},fc:c})},nb=(a,b,c,d,e)=>J({target:a,dc:e,hc:d,ic:(g=event)=>{L(d)(38,0,b)&&g.preventDefault()},fc:c}),ob=(a,b,c,d)=>{I.Bc||(I.Bc=N(36));a=K(a);return J({target:a,dc:"resize",hc:d,ic:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=I.Bc;v[f>>
2]=0;v[f+4>>2]=g.clientWidth;v[f+8>>2]=g.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;L(d)(10,f,b)&&e.preventDefault()}}},fc:c})},pb=(a,b,c,d,e,g)=>{I.Ac||(I.Ac=N(1552));a=K(a);return J({target:a,uc:"touchstart"==g||"touchend"==g,dc:g,hc:d,ic:f=>{var l={},n=f.touches;for(var q of n)q.Kc=q.Mc=0,l[q.identifier]=q;for(var t of f.changedTouches)t.Kc=1,l[t.identifier]=t;for(var sa of f.targetTouches)l[sa.identifier].Mc=
1;n=I.Ac;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;q=n+16;t=gb(a);sa=0;for(let F of Object.values(l))if(l=q>>2,v[l]=F.identifier,v[l+1]=F.screenX,v[l+2]=F.screenY,v[l+3]=F.clientX,v[l+4]=F.clientY,v[l+5]=F.pageX,v[l+6]=F.pageY,r[q+28]=F.Kc,r[q+29]=F.Mc,v[l+8]=F.clientX-(t.left|0),v[l+9]=F.clientY-(t.top|0),q+=48,31<++sa)break;v[n+8>>2]=sa;L(d)(e,n,b)&&f.preventDefault()},fc:c})},P,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=
(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},rb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,
d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ub=1,Q=[],R=[],vb=[],wb=[],xb=[],S=[],yb=[],zb=[],T=[],Ab={},Bb=4,Cb=0,Db=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},Eb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=P[c](),f=g&&Db(d);g?(g.name=f,d[f]=g):U||=1282;v[b+4*e>>2]=f}},Gb=(a,b)=>{a.lc||(a.lc=a.getContext,a.getContext=function(d,e){e=a.lc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Lc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Fb(c,b):0},Fb=(a,b)=>{var c=Db(zb),d={handle:c,attributes:b,version:b.Lc,Ec:a};a.canvas&&(a.canvas.$c=d);zb[c]=d;("undefined"==typeof b.Ic||b.Ic)&&Hb(d);return c},Hb=a=>{a||=V;if(!a.Zc){a.Zc=!0;var b=a.Ec;b.sd=b.getExtension("WEBGL_multi_draw");b.ld=b.getExtension("EXT_polygon_offset_clamp");b.kd=b.getExtension("EXT_clip_control");b.Dd=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);b.hd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.pd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Hc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Hc)b.Hc=b.getExtension("EXT_disjoint_timer_query");tb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Ib=(a,b,c,d,e,g)=>{a={target:K(a),dc:g,hc:d,ic:(f=event)=>{L(d)(e,0,b)&&f.preventDefault()},fc:c};J(a)},Jb=(a,b,c,d)=>{I.Dc||(I.Dc=N(96));return J({target:a,uc:!0,dc:"wheel",hc:d,ic:(e=event)=>{var g=I.Dc;lb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+80>>3]=e.deltaZ;
v[g+88>>2]=e.deltaMode;L(d)(9,g,b)&&e.preventDefault()},fc:c})},Kb=["default","low-power","high-performance"],Lb={},Nb=()=>{if(!Mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Lb)void 0===Lb[b]?delete a[b]:a[b]=Lb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Mb=c}return Mb},Mb,Ob=[null,[],[]],Pb=()=>{var a=tb(P);return a=
a.concat(a.map(b=>"GL_"+b))},Qb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Pb().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else U||=1281},Rb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Sb=a=>{var b=Rb(a)+1,c=N(b);c&&M(a,c,b);return c},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=[],Vb=a=>{a-=5120;return 0==a?r:1==a?u:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:qa},W=a=>{var b=P.Xc;if(b){var c=b.nc[a];"number"==typeof c&&(b.nc[a]=c=P.getUniformLocation(b,b.Uc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],Wb=[],Yb=a=>{var b=Rb(a)+
1,c=Xb(b);M(a,c,b);return c},ac=a=>{var b=Zb();a();$b(b)};h.requestAnimationFrame=Qa;h.pauseMainLoop=bb;h.resumeMainLoop=function(){Ta++;var a=Ma,b=Na,c=D;D=null;ab(c,0,!1,Ua,!0);Sa(a,b);E()};h.preMainLoop&&Za.push(h.preMainLoop);h.postMainLoop&&$a.push(h.postMainLoop);for(var Y=0;32>Y;++Y)Ub.push(Array(Y));var bc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=bc.subarray(0,Y);var cc=new Int32Array(288);for(Y=0;288>=Y;++Y)Wb[Y]=cc.subarray(0,Y);
var jc={da:function(){return 0},mb:function(){return 0},nb:function(){},Za:()=>ua(""),fb:()=>{Fa=!1;Ga=0},gb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];La(()=>dc(a,performance.now()))},b);C[a]={id:c,Bd:b};return 0},hb:function(a,b,c){if(!(0<=a&&3>=a))return 28;ra[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},Ta:()=>{bb();D=null},J:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,P:(a,b,c)=>{a=K(a);if(!a)return-4;
a=gb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Ua:()=>performance.now(),_a:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Pb:()=>{ua("OOM")},Q:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),F:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),_:(a,b,c,d)=>kb(a,b,c,d,2,"keydown"),Y:(a,b,c,d)=>kb(a,b,c,d,1,"keypress"),Z:(a,b,c,d)=>kb(a,b,c,d,3,"keyup"),$a:(a,b,c)=>{a=L(a);ab(a,b,c)},ma:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),
ga:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),ha:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),ia:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.lc||document.body.pc||document.body.oc))return-1;a=K(a);if(!a)return-4;mb(a,b,c,d,"mozpointerlockchange");mb(a,b,c,d,"webkitpointerlockchange");mb(a,b,c,d,"mspointerlockchange");return mb(a,b,c,d,"pointerlockchange")},S:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||
document.body.lc||document.body.pc||document.body.oc))return-1;a=K(a);if(!a)return-4;nb(a,b,c,d,"mozpointerlockerror");nb(a,b,c,d,"webkitpointerlockerror");nb(a,b,c,d,"mspointerlockerror");return nb(a,b,c,d,"pointerlockerror")},M:(a,b,c,d)=>ob(a,b,c,d),U:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),V:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),W:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),X:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),O:(a,b,c,d)=>{Ib(a,b,c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{Ib(a,b,c,d,32,
"webglcontextrestored");return 0},$:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Jb(a,b,c,d):-1:-4,ya:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Kb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Lc:v[c+4],rd:v[c+5],Ic:r[b+24],Yc:r[b+25],ud:v[c+7],yd:r[b+32]};a=K(a);return!a||b.Yc?0:Gb(a,b)},ua:a=>{V=zb[a];h.ctx=P=V?.Ec;return!a||P?0:-5},ib:(a,b)=>{var c=0;Nb().forEach((d,e)=>
{var g=b+c;e=w[a+4*e>>2]=g;for(g=0;g<d.length;++g)r[e++]=d.charCodeAt(g);r[e]=0;c+=d.length+1});return 0},jb:(a,b)=>{var c=Nb();w[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w[b>>2]=d;return 0},ba:()=>52,lb:()=>52,kb:function(){return 70},na:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=u[f+n],t=Ob[a];0===q||10===q?((1===a?la:m)(z(t)),t.length=0):t.push(q)}e+=l}w[d>>2]=e;return 0},t:a=>P.activeTexture(a),q:(a,b)=>{P.attachShader(R[a],S[b])},
b:(a,b)=>{35051==a?P.Gc=b:35052==a&&(P.mc=b);P.bindBuffer(a,Q[b])},d:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},m:(a,b)=>{P.bindFramebuffer(a,vb[b])},Ia:(a,b)=>{P.bindRenderbuffer(a,wb[b])},s:(a,b)=>{P.bindSampler(a,T[b])},g:(a,b)=>{P.bindTexture(a,xb[b])},L:a=>{P.bindVertexArray(yb[a])},u:(a,b,c,d)=>P.blendColor(a,b,c,d),v:(a,b)=>P.blendEquationSeparate(a,b),w:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),wb:(a,b,c,d,e,g,f,l,n,q)=>P.blitFramebuffer(a,b,c,d,e,g,f,l,n,q),Ka:(a,b,c,d)=>{2<=V.version?c&&b?P.bufferData(a,
u,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?u.subarray(c,c+b):b,d)},G:(a,b,c,d)=>{2<=V.version?c&&P.bufferSubData(a,b,u,d,c):P.bufferSubData(a,b,u.subarray(d,d+c))},ra:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),y:(a,b,c)=>{P.clearBufferfv(a,b,x,c>>2)},qa:(a,b,c)=>{P.clearBufferiv(a,b,v,c>>2)},h:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},pb:a=>{P.compileShader(S[a])},Ba:(a,b,c,d,e,g,f,l)=>{2<=V.version?P.mc||!f?P.compressedTexImage2D(a,b,c,d,e,g,f,l):P.compressedTexImage2D(a,b,c,d,e,g,u,l,f):P.compressedTexImage2D(a,
b,c,d,e,g,u.subarray(l,l+f))},Da:(a,b,c,d,e,g,f,l,n)=>{P.mc?P.compressedTexImage3D(a,b,c,d,e,g,f,l,n):P.compressedTexImage3D(a,b,c,d,e,g,f,u,n,l)},wa:()=>{var a=Db(R),b=P.createProgram();b.name=a;b.sc=b.qc=b.rc=0;b.Cc=1;R[a]=b;return a},rb:a=>{var b=Db(S);S[b]=P.createShader(a);return b},la:a=>P.cullFace(a),sb:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.Gc&&(P.Gc=0),d==P.mc&&(P.mc=0))}},j:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=vb[d];
e&&(P.deleteFramebuffer(e),e.name=0,vb[d]=null)}},k:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},I:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=wb[d];e&&(P.deleteRenderbuffer(e),e.name=0,wb[d]=null)}},H:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=T[d];e&&(P.deleteSampler(e),e.name=0,T[d]=null)}},i:a=>{if(a){var b=S[a];b?(P.deleteShader(b),S[a]=null):U||=1281}},K:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=xb[d];e&&(P.deleteTexture(e),e.name=0,xb[d]=null)}},
Ma:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];P.deleteVertexArray(yb[d]);yb[d]=null}},o:a=>P.depthFunc(a),p:a=>{P.depthMask(!!a)},c:a=>P.disable(a),ja:a=>{P.disableVertexAttribArray(a)},yb:(a,b,c)=>{P.drawArrays(a,b,c)},zb:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},Bb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},Ab:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},f:a=>P.enable(a),Lb:a=>{P.enableVertexAttribArray(a)},ka:a=>P.frontFace(a),La:(a,b)=>{Eb(a,b,"createBuffer",Q)},Ja:(a,b)=>{Eb(a,b,"createRenderbuffer",
wb)},xa:(a,b)=>{Eb(a,b,"createSampler",T)},Ga:(a,b)=>{Eb(a,b,"createTexture",xb)},Oa:(a,b)=>{Eb(a,b,"createVertexArray",yb)},sa:(a,b)=>P.getAttribLocation(R[a],b?z(u,b):""),a:(a,b)=>Qb(a,b),va:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(v[c>>2]=b)},C:(a,b,c)=>{if(c)if(a>=ub)U||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.sc){var d=P.getProgramParameter(a,35718);
for(b=0;b<d;++b)a.sc=Math.max(a.sc,P.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.sc}else if(35722==b){if(!a.qc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.qc=Math.max(a.qc,P.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.qc}else if(35381==b){if(!a.rc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.rc=Math.max(a.rc,P.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.rc}else v[c>>2]=P.getProgramParameter(a,b);else U||=1281},ob:(a,b,c,d)=>{a=P.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");
b=0<b&&d?M(a,d,b):0;c&&(v[c>>2]=b)},fa:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(S[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=P.getShaderParameter(S[a],b):U||=1281},Pa:(a,b)=>{if(2>V.version)return U||=1282,0;var c=Ab[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Pb().map(Sb),c=Ab[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},B:(a,b)=>{b=b?z(u,b):"";if(a=R[a]){var c=
a,d=c.nc,e=c.Vc,g;if(!d){c.nc=d={};c.Uc={};var f=P.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=P.getActiveUniform(c,g);var n=l.name;l=l.size;var q=Tb(n);q=0<q?n.slice(0,q):n;var t=c.Cc;c.Cc+=l;e[q]=[l,t];for(n=0;n<l;++n)d[t]=n,c.Uc[t++]=q}}c=a.nc;d=0;e=b;g=Tb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Vc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else U||=1281;return-1},vb:(a,b,c)=>{for(var d=Ub[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];P.invalidateFramebuffer(a,
d)},D:a=>{a=R[a];P.linkProgram(a);a.nc=0;a.Vc={}},Na:(a,b)=>{3317==a?Bb=b:3314==a&&(Cb=b);P.pixelStorei(a,b)},x:(a,b)=>P.polygonOffset(a,b),xb:a=>P.readBuffer(a),Ha:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),E:(a,b,c)=>{P.samplerParameterf(T[a],b,c)},e:(a,b,c)=>{P.samplerParameteri(T[a],b,c)},z:(a,b,c,d)=>P.scissor(a,b,c,d),qb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=w[c+4*g>>2])?z(u,f,d?w[d+4*g>>2]:void 0):"";e+=f}P.shaderSource(S[a],e)},ub:(a,b,c)=>P.stencilFunc(a,b,c),pa:(a,
b,c,d)=>P.stencilFuncSeparate(a,b,c,d),n:a=>P.stencilMask(a),tb:(a,b,c)=>P.stencilOp(a,b,c),oa:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),Aa:(a,b,c,d,e,g,f,l,n)=>{if(2<=V.version){if(P.mc){P.texImage2D(a,b,c,d,e,g,f,l,n);return}if(n){var q=Vb(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,g,f,l,q,n);return}}if(n){q=Vb(l);var t=e*((Cb||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+Bb-1&-Bb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),
n+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;P.texImage2D(a,b,c,d,e,g,f,l,n)},Ca:(a,b,c,d,e,g,f,l,n,q)=>{if(P.mc)P.texImage3D(a,b,c,d,e,g,f,l,n,q);else if(q){var t=Vb(n);P.texImage3D(a,b,c,d,e,g,f,l,n,t,q>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,g,f,l,n,null)},Fa:(a,b,c)=>P.texParameteri(a,b,c),za:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),Ea:(a,b,c,d,e,g)=>P.texStorage3D(a,b,c,d,e,g),Kb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=
X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},ta:(a,b)=>{P.uniform1i(W(a),b)},Gb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Wb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},Jb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},
Fb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Wb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},Ib:(a,b,c)=>{if(2<=V.version)b&&P.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);P.uniform3fv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=
b){b*=3;for(var d=Wb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},Hb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},Db:(a,b,c)=>{if(2<=V.version)b&&P.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Wb[b],
e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},Cb:(a,b,c,d)=>{if(2<=V.version)b&&P.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],g=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=
g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=R[a];P.useProgram(a);P.Xc=a},Mb:(a,b)=>{P.vertexAttribDivisor(a,b)},Nb:(a,b,c,d,e)=>{P.vertexAttribIPointer(a,b,c,d,e)},Ob:(a,b,c,d,e,g)=>{P.vertexAttribPointer(a,b,c,!!d,e,g)},A:(a,b,c,d)=>P.viewport(a,b,c,d),eb:Ia,cb:function(){h.Oc=a=>{0!=ec()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Oc)},bb:function(){h.Tc=a=>{const b=a.clipboardData.getData("text");
ac(()=>{const c=Yb(b);fc(c)})};window.addEventListener("paste",h.Tc)},ab:function(){h.zd=[];h.Pc=b=>{b.stopPropagation();b.preventDefault()};h.Qc=b=>{b.stopPropagation();b.preventDefault()};h.Rc=b=>{b.stopPropagation();b.preventDefault()};h.Sc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.Ad=c;gc(c.length);for(let e=0;e<c.length;e++)ac(()=>{const g=Yb(c[e].name);hc(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ic(b.clientX,b.clientY,
d)};const a=h.jc;a.addEventListener("dragenter",h.Pc,!1);a.addEventListener("dragleave",h.Qc,!1);a.addEventListener("dragover",h.Rc,!1);a.addEventListener("drop",h.Sc,!1)},Wa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},db:function(a,b){0!==b&&(document.title=b?z(u,b):"");a=a?z(u,a):"";void 0!==h.canvas&&("object"===typeof h.canvas?fb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.jc=K(a);h.jc||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);h.jc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Sa:function(){window.removeEventListener("beforeunload",h.Oc)},Ra:function(){window.removeEventListener("paste",h.Tc)},Qa:function(){const a=h.jc;a.removeEventListener("dragenter",h.Pc);a.removeEventListener("dragleave",h.Qc);a.removeEventListener("dragover",h.Rc);a.removeEventListener("drop",h.Sc)},r:function(){h.jc&&h.jc.requestPointerLock&&h.jc.requestPointerLock()},Ya:function(a,b){if(h.jc){if(0===
b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.jc.style.cursor=a}},Va:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(u.subarray(c,
c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Xa:function(a){a=a?z(u,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();
document.execCommand("copy");document.body.removeChild(b)},ea:function(){return navigator.userAgent.includes("Macintosh")?1:0},aa:function(a,b){b=b?z(u,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;na=Z.Qb;c=na.buffer;h.HEAP8=r=new Int8Array(c);h.HEAP16=pa=new Int16Array(c);h.HEAPU8=u=new Uint8Array(c);h.HEAPU16=qa=new Uint16Array(c);h.HEAP32=v=new Int32Array(c);h.HEAPU32=w=new Uint32Array(c);h.HEAPF32=x=new Float32Array(c);h.HEAPF64=y=new Float64Array(c);h.HEAP64=ra=new BigInt64Array(c);h.HEAPU64=new BigUint64Array(c);ib=Z.cc;A--;h.monitorRunDependencies?.(A);0==A&&B&&(c=B,B=null,c());return Z}A++;h.monitorRunDependencies?.(A);var b={a:jc};if(h.instantiateWasm)return new Promise(c=>
{h.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});va??=h.locateFile?h.locateFile("demo.wasm",k):k+"demo.wasm";return a((await ya(b)).instance)})();
var kc=h._main=(a,b)=>(kc=h._main=Z.Sb)(a,b),fc=h.__sapp_emsc_onpaste=a=>(fc=h.__sapp_emsc_onpaste=Z.Tb)(a),ec=h.__sapp_html5_get_ask_leave_site=()=>(ec=h.__sapp_html5_get_ask_leave_site=Z.Ub)(),gc=h.__sapp_emsc_begin_drop=a=>(gc=h.__sapp_emsc_begin_drop=Z.Vb)(a),hc=h.__sapp_emsc_drop=(a,b)=>(hc=h.__sapp_emsc_drop=Z.Wb)(a,b),ic=h.__sapp_emsc_end_drop=(a,b,c)=>(ic=h.__sapp_emsc_end_drop=Z.Xb)(a,b,c);
h.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,g,f,l)=>(h.__sapp_emsc_invoke_fetch_cb=Z.Yb)(a,b,c,d,e,g,f,l);var dc=(a,b)=>(dc=Z.Zb)(a,b),N=a=>(N=Z._b)(a),$b=a=>($b=Z.$b)(a),Xb=a=>(Xb=Z.ac)(a),Zb=()=>(Zb=Z.bc)();function lc(a=[]){var b=kc;a.unshift(fa);var c=a.length,d=Xb(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Yb(f);e+=4});w[e>>2]=0;try{var g=b(c,d);Ja(g)}catch(f){Ha(f)}}
function mc(a=ea){function b(){h.calledRun=!0;if(!p){Z.Rb();h.onRuntimeInitialized?.();h.noInitialRun||lc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Ca.unshift(c)}Ba(Ca)}}if(0<A)B=mc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ea();Ba(Da);0<A?B=mc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();mc();
